version: '3'
services:
  api:
    image: pi0neerpat/redwood-devops-example-api:latest
    ports:
      - '8911:8911'
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    env_file:
      - .env
    environment:
      REDWOOD_API_URL: 'http://0.0.0.0:8911'

  web:
    image: pi0neerpat/redwood-devops-example-web:latest
    ports:
      - '8910:8910' # http
    depends_on:
      - api
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    # env_file:
    #   - .env
